version: '3'

services:
  lockio-db:
    image: mysql:8
    container_name: lockio-db
    environment:
      - MYSQL_USER=dev
      - MYSQL_DATABASE=lockio
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci